### PR TITLE
Fixes

### LINKED ISSUE #70: Incorrect spend authorization signatures returned by hardware wallet
The call `get_spend_signature()` returns incorrect spend signatures when the number of generated spend randomness parameters (equal to the number of calls to `get_spend_randomness()`) exceeds the number of spend descriptions (equal to the number of spend authorization signatures pushed). It seems that this is due to how the hardware wallet internally indexes the spend authorization signatures it is fetching here: https://github.com/Zondax/ledger-namada/blob/5ed06a4d6d3347e301cf5afc02aba0e319eef57a/app/src/nvdata.c#L140 .

### PR DESCRIPTION
**Pull request by chcmedeiros**
- fixes on the convert checks
- improving rs lib
- add shielded hash verification for maspTx and Ibc
closes #70 #72 #74 #76 #78 #66

### CODE REVIEW

**Review by abenso — APPROVED** [review]

File: app/src/crypto.c [hunk 1]
```diff
@@ -733,19 +733,23 @@ zxerr_t crypto_extract_spend_signature(uint8_t *buffer, uint16_t bufferLen, uint
...
+    for (uint32_t i = 0; i < txObj->transaction.sections.maspBuilder.metadata.n_spends_indices; i++) {
         CHECK_ERROR(getNextSpendDescription(builder_spends_ctx, i));
-        CTX_CHECK_AND_ADVANCE(tx_spends_ctx, SHIELDED_SPENDS_LEN * i);
-        spend_item_t *item = spendlist_retrieve_rand_item(i);
+
+        uint64_t indice = 0;
+        CHECK_ERROR(readUint64(indices_ctx, &indice));
+
+        CTX_CHECK_AND_ADVANCE(tx_spends_ctx, SHIELDED_SPENDS_LEN * indice);
+        spend_item_t *item = spendlist_retrieve_rand_item(indice);
```
Comment (emmanuelm41) [inline app/src/crypto.c:752]: We were previously doing SHIELDAD_SPENDS_LEN * i, and now it is SHIELD_SPENDS_LEN * indice. Is that correct? I assume there is some correlation between i and indice, right?

File: app/src/crypto.c [hunk 2]
```diff
@@ -782,69 +786,84 @@ parser_error_t checkOutputs(const parser_tx_t *txObj, parser_context_t *builder_
...
+        for (i = 0; i < txObj->transaction.sections.maspBuilder.metadata.n_outputs_indices; i++) {
+            uint64_t curr_indice;
+            CHECK_ERROR(readUint64(indices_ctx, &curr_indice));
+            if (curr_indice == indice) break;
+        }
         CTX_CHECK_AND_ADVANCE(tx_outputs_ctx, SHIELDED_OUTPUTS_LEN * indice);
         output_item_t *item = outputlist_retrieve_rand_item(indice);
+        uint64_t value = 0;
+        // Use the dummy note identifier as the default
+        uint8_t identifier[IDENTIFIER_LEN] = {156, 229, 191, 54, 209, 138, 169, 235, 234, 174, 120, 186, 142, 34, 183, 118, 64, 243, 100, 134, 234, 27, 248, 27, 36, 245, 9, 146, 30, 110, 203, 169};
```
Comment (emmanuelm41) [inline app/src/crypto.c:806]: Shouldn't we move this to the outside as some CONST?

File: app/src/nvdata.c [hunk 3]
```diff
@@ -120,42 +120,40 @@ uint8_t transaction_get_n_converts() {
...
+  if (index >= transaction_header.spends_sign_len) {
     return zxerr_unknown;
   }
   MEMCPY(result, (void *)&N_transactioninfo.spend_signatures[index], SIGNATURE_SIZE);
-  transaction_header.spends_sign_index--;
-  if (!spend_signatures_more_extract()) {
-    transaction_reset();
-  }
+  transaction_header.spends_sign_index++;
   return zxerr_ok;
```
Comment (emmanuelm41) [inline app/src/nvdata.c:146]: Shouldn't we keep the check for spend_signatures_more_extract, as it was refactored to match the new logic? (increase instead of decrease)

File: app/src/parser_impl_masp.c [hunk 4]
```diff
@@ -332,6 +336,14 @@ static parser_error_t readSaplingOutputDescriptionInfo(parser_context_t *ctx, ma
...
 
     CHECK_ERROR(readUint32(ctx, &builder->n_outputs))
+#if defined(LEDGER_SPECIFIC) && !defined(APP_TESTING)
+    if (G_io_apdu_buffer[OFFSET_INS] == INS_SIGN_MASP_SPENDS) {
+        uint32_t rnd_outputs = (uint32_t)transaction_get_n_outputs();
+        if (rnd_outputs < builder->n_outputs) {
+            return parser_invalid_number_of_outputs;
+        }
+    }
+#endif
```
Comment (emmanuelm41) [inline app/src/parser_impl_masp.c:346]: This seems like something we can extract to a function, as it is repeated in many places. Not sure if stack usage will allow us to do it or not.

**Review by emmanuelm41 — COMMENTED** [review]
Just left a few comments. I did my best to review the code using the knowledge I have about namada. Just wonder if it is correct the zemu snapshots are so different.

File: app/src/crypto.c (hunk 1 above)
Comment (chcmedeiros) [reply app/src/crypto.c:752]: Yes that is correct. The i will go through all the spends in the tx, and the indice, through an array of the actual spends index that should be checked. I just notice this might be wrong, so I will redo the logic, the one used in the outputs that is the correct one.

File: app/src/nvdata.c (hunk 3 above)
Comment (chcmedeiros) [reply app/src/nvdata.c:146]: That is the check that is being done, but I was not calling spend_signatures_more_extract, I will replace the logic with a call to that function.

**Review by emmanuelm41 — APPROVED** [review]
